CUDNN:
  BENCHMARK: false
  DETERMINISTIC: false
  ENABLED: true

WORKERS: 4
PRINT_FREQ: 100
DISTANCE: 3

DATASET:
  NAME: "PoseTrack_5_frame"
  JSON_DIR: "./DcPose_supp_files/posetrack17_json_files"
  IMG_DIR: "./Dataset/PoseTrack2017/images_renamed"
#  TEST_IMG_DIR: "./Dataset/PoseTrack2017/images_renamed"
  TEST_IMG_DIR: "./Dataset/PoseTrack2017/posetrack_data/images"
  IS_POSETRACK18: false
  COLOR_RGB: true
  DATASET: 'posetrack'
  ROOT: ''
  TEST_SET: 'val2017'
  TRAIN_SET: 'train2017'
  # INPUT_TYPE in ['single_frame','spatiotemporal_window']
  INPUT_TYPE: 'spatiotemporal_window'
  BBOX_ENLARGE_FACTOR: 1.25




MODEL:
  FREEZE_BACKBONE_WEIGHTS: true
  EVALUATE: true
  INIT_WEIGHTS: true

  NUM_JOINTS: 17
  PRETRAINED: './pretrain/17/vit_17.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
    - 192
    - 256
  HEATMAP_SIZE:
    - 48
    - 64
  SIGMA: 3
  USE_RECTIFIER: true


TRAIN:
  FLIP: true
  NUM_JOINTS_HALF_BODY: 8
  PROB_HALF_BODY: 0.3
  ROT_FACTOR: 45
  SCALE_FACTOR: [ 0.35,0.35 ]
  SHUFFLE: true

  MOMENTUM: 0.9
  NESTEROV: false

VAL:
  ANNOT_DIR: './DcPose_supp_files/posetrack17_annotation_dirs/jsons/val/'
  COCO_BBOX_FILE: './DcPose_supp_files/posetrack17_precomputed_boxes/ConvNext_posetrack17_val_boxes.json'
  USE_GT_BBOX: false
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.2
  IN_VIS_THRE: 0.2
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_VAL: false
  POST_PROCESS: true

TEST:
  ANNOT_DIR: './DcPose_supp_files/posetrack17_annotation_dirs/jsons/test'
  COCO_BBOX_FILE: './DcPose_supp_files/posetrack17_precomputed_boxes/test_boxes.json'
  USE_GT_BBOX: false
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.2
  IN_VIS_THRE: 0.2
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  FLIP_TEST: false
  POST_PROCESS: true